//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWA.SoftProgServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="pe.edu.pucp.softprog.services", ConfigurationName="SoftProgServices.AreaWS")]
    public interface AreaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/insertarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/insertarAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.insertarAreaResponse insertarArea(SoftProgWA.SoftProgServices.insertarAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/insertarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/insertarAreaResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarAreaResponse> insertarAreaAsync(SoftProgWA.SoftProgServices.insertarAreaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/obtenerAreaPorIdRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/obtenerAreaPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse obtenerAreaPorId(SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/obtenerAreaPorIdRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/obtenerAreaPorIdResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse> obtenerAreaPorIdAsync(SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/listarAreasTodasRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/listarAreasTodasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.listarAreasTodasResponse listarAreasTodas(SoftProgWA.SoftProgServices.listarAreasTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/listarAreasTodasRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/listarAreasTodasResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarAreasTodasResponse> listarAreasTodasAsync(SoftProgWA.SoftProgServices.listarAreasTodasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/modificarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/modificarAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.modificarAreaResponse modificarArea(SoftProgWA.SoftProgServices.modificarAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/modificarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/modificarAreaResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.modificarAreaResponse> modificarAreaAsync(SoftProgWA.SoftProgServices.modificarAreaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/eliminarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/eliminarAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.eliminarAreaResponse eliminarArea(SoftProgWA.SoftProgServices.eliminarAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/eliminarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/eliminarAreaResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.eliminarAreaResponse> eliminarAreaAsync(SoftProgWA.SoftProgServices.eliminarAreaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe.edu.pucp.softprog.services")]
    public partial class area : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idAreaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idArea {
            get {
                return this.idAreaField;
            }
            set {
                this.idAreaField = value;
                this.RaisePropertyChanged("idArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarArea", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class insertarAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.area arg0;
        
        public insertarAreaRequest() {
        }
        
        public insertarAreaRequest(SoftProgWA.SoftProgServices.area arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAreaResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class insertarAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarAreaResponse() {
        }
        
        public insertarAreaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAreaPorId", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class obtenerAreaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idArea;
        
        public obtenerAreaPorIdRequest() {
        }
        
        public obtenerAreaPorIdRequest(int idArea) {
            this.idArea = idArea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAreaPorIdResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class obtenerAreaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.area @return;
        
        public obtenerAreaPorIdResponse() {
        }
        
        public obtenerAreaPorIdResponse(SoftProgWA.SoftProgServices.area @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAreasTodas", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class listarAreasTodasRequest {
        
        public listarAreasTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAreasTodasResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class listarAreasTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.area[] @return;
        
        public listarAreasTodasResponse() {
        }
        
        public listarAreasTodasResponse(SoftProgWA.SoftProgServices.area[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarArea", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class modificarAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.area arg0;
        
        public modificarAreaRequest() {
        }
        
        public modificarAreaRequest(SoftProgWA.SoftProgServices.area arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAreaResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class modificarAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarAreaResponse() {
        }
        
        public modificarAreaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarArea", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class eliminarAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarAreaRequest() {
        }
        
        public eliminarAreaRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAreaResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class eliminarAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarAreaResponse() {
        }
        
        public eliminarAreaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AreaWSChannel : SoftProgWA.SoftProgServices.AreaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AreaWSClient : System.ServiceModel.ClientBase<SoftProgWA.SoftProgServices.AreaWS>, SoftProgWA.SoftProgServices.AreaWS {
        
        public AreaWSClient() {
        }
        
        public AreaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AreaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.insertarAreaResponse SoftProgWA.SoftProgServices.AreaWS.insertarArea(SoftProgWA.SoftProgServices.insertarAreaRequest request) {
            return base.Channel.insertarArea(request);
        }
        
        public int insertarArea(SoftProgWA.SoftProgServices.area arg0) {
            SoftProgWA.SoftProgServices.insertarAreaRequest inValue = new SoftProgWA.SoftProgServices.insertarAreaRequest();
            inValue.arg0 = arg0;
            SoftProgWA.SoftProgServices.insertarAreaResponse retVal = ((SoftProgWA.SoftProgServices.AreaWS)(this)).insertarArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarAreaResponse> SoftProgWA.SoftProgServices.AreaWS.insertarAreaAsync(SoftProgWA.SoftProgServices.insertarAreaRequest request) {
            return base.Channel.insertarAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarAreaResponse> insertarAreaAsync(SoftProgWA.SoftProgServices.area arg0) {
            SoftProgWA.SoftProgServices.insertarAreaRequest inValue = new SoftProgWA.SoftProgServices.insertarAreaRequest();
            inValue.arg0 = arg0;
            return ((SoftProgWA.SoftProgServices.AreaWS)(this)).insertarAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse SoftProgWA.SoftProgServices.AreaWS.obtenerAreaPorId(SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest request) {
            return base.Channel.obtenerAreaPorId(request);
        }
        
        public SoftProgWA.SoftProgServices.area obtenerAreaPorId(int idArea) {
            SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest inValue = new SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest();
            inValue.idArea = idArea;
            SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse retVal = ((SoftProgWA.SoftProgServices.AreaWS)(this)).obtenerAreaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse> SoftProgWA.SoftProgServices.AreaWS.obtenerAreaPorIdAsync(SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest request) {
            return base.Channel.obtenerAreaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse> obtenerAreaPorIdAsync(int idArea) {
            SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest inValue = new SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest();
            inValue.idArea = idArea;
            return ((SoftProgWA.SoftProgServices.AreaWS)(this)).obtenerAreaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.listarAreasTodasResponse SoftProgWA.SoftProgServices.AreaWS.listarAreasTodas(SoftProgWA.SoftProgServices.listarAreasTodasRequest request) {
            return base.Channel.listarAreasTodas(request);
        }
        
        public SoftProgWA.SoftProgServices.area[] listarAreasTodas() {
            SoftProgWA.SoftProgServices.listarAreasTodasRequest inValue = new SoftProgWA.SoftProgServices.listarAreasTodasRequest();
            SoftProgWA.SoftProgServices.listarAreasTodasResponse retVal = ((SoftProgWA.SoftProgServices.AreaWS)(this)).listarAreasTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarAreasTodasResponse> SoftProgWA.SoftProgServices.AreaWS.listarAreasTodasAsync(SoftProgWA.SoftProgServices.listarAreasTodasRequest request) {
            return base.Channel.listarAreasTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarAreasTodasResponse> listarAreasTodasAsync() {
            SoftProgWA.SoftProgServices.listarAreasTodasRequest inValue = new SoftProgWA.SoftProgServices.listarAreasTodasRequest();
            return ((SoftProgWA.SoftProgServices.AreaWS)(this)).listarAreasTodasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.modificarAreaResponse SoftProgWA.SoftProgServices.AreaWS.modificarArea(SoftProgWA.SoftProgServices.modificarAreaRequest request) {
            return base.Channel.modificarArea(request);
        }
        
        public int modificarArea(SoftProgWA.SoftProgServices.area arg0) {
            SoftProgWA.SoftProgServices.modificarAreaRequest inValue = new SoftProgWA.SoftProgServices.modificarAreaRequest();
            inValue.arg0 = arg0;
            SoftProgWA.SoftProgServices.modificarAreaResponse retVal = ((SoftProgWA.SoftProgServices.AreaWS)(this)).modificarArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.modificarAreaResponse> SoftProgWA.SoftProgServices.AreaWS.modificarAreaAsync(SoftProgWA.SoftProgServices.modificarAreaRequest request) {
            return base.Channel.modificarAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.modificarAreaResponse> modificarAreaAsync(SoftProgWA.SoftProgServices.area arg0) {
            SoftProgWA.SoftProgServices.modificarAreaRequest inValue = new SoftProgWA.SoftProgServices.modificarAreaRequest();
            inValue.arg0 = arg0;
            return ((SoftProgWA.SoftProgServices.AreaWS)(this)).modificarAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.eliminarAreaResponse SoftProgWA.SoftProgServices.AreaWS.eliminarArea(SoftProgWA.SoftProgServices.eliminarAreaRequest request) {
            return base.Channel.eliminarArea(request);
        }
        
        public int eliminarArea(int arg0) {
            SoftProgWA.SoftProgServices.eliminarAreaRequest inValue = new SoftProgWA.SoftProgServices.eliminarAreaRequest();
            inValue.arg0 = arg0;
            SoftProgWA.SoftProgServices.eliminarAreaResponse retVal = ((SoftProgWA.SoftProgServices.AreaWS)(this)).eliminarArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.eliminarAreaResponse> SoftProgWA.SoftProgServices.AreaWS.eliminarAreaAsync(SoftProgWA.SoftProgServices.eliminarAreaRequest request) {
            return base.Channel.eliminarAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.eliminarAreaResponse> eliminarAreaAsync(int arg0) {
            SoftProgWA.SoftProgServices.eliminarAreaRequest inValue = new SoftProgWA.SoftProgServices.eliminarAreaRequest();
            inValue.arg0 = arg0;
            return ((SoftProgWA.SoftProgServices.AreaWS)(this)).eliminarAreaAsync(inValue);
        }
    }
}
