//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWA.SoftProgServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="pe.edu.pucp.softprog.services", ConfigurationName="SoftProgServices.ClienteWS")]
    public interface ClienteWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/ClienteWS/listarClientesPorDNIoNombreRequest", ReplyAction="pe.edu.pucp.softprog.services/ClienteWS/listarClientesPorDNIoNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreResponse listarClientesPorDNIoNombre(SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/ClienteWS/listarClientesPorDNIoNombreRequest", ReplyAction="pe.edu.pucp.softprog.services/ClienteWS/listarClientesPorDNIoNombreResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreResponse> listarClientesPorDNIoNombreAsync(SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe.edu.pucp.softprog.services")]
    public partial class cliente : persona {
        
        private categoria categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private double lineaCreditoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoria categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double lineaCredito {
            get {
                return this.lineaCreditoField;
            }
            set {
                this.lineaCreditoField = value;
                this.RaisePropertyChanged("lineaCredito");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe.edu.pucp.softprog.services")]
    public enum categoria {
        
        /// <remarks/>
        Clasico,
        
        /// <remarks/>
        VIP,
        
        /// <remarks/>
        Gold,
        
        /// <remarks/>
        Platinum,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe.edu.pucp.softprog.services")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private int idPersonaField;
        
        private string nombreField;
        
        private ushort sexoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ushort sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe.edu.pucp.softprog.services")]
    public partial class cuentaUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private empleado empleadoField;
        
        private int idCuentaUsuarioField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public empleado empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("empleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCuentaUsuario {
            get {
                return this.idCuentaUsuarioField;
            }
            set {
                this.idCuentaUsuarioField = value;
                this.RaisePropertyChanged("idCuentaUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe.edu.pucp.softprog.services")]
    public partial class empleado : persona {
        
        private bool activoField;
        
        private area areaField;
        
        private string cargoField;
        
        private double sueldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public area area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double sueldo {
            get {
                return this.sueldoField;
            }
            set {
                this.sueldoField = value;
                this.RaisePropertyChanged("sueldo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe.edu.pucp.softprog.services")]
    public partial class area : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idAreaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idArea {
            get {
                return this.idAreaField;
            }
            set {
                this.idAreaField = value;
                this.RaisePropertyChanged("idArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe.edu.pucp.softprog.services")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idProductoField;
        
        private string nombreField;
        
        private double precioField;
        
        private string unidadMedidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string unidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("unidadMedida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe.edu.pucp.softprog.services")]
    public partial class lineaOrdenVenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int cantidadField;
        
        private int idLineaOrdenVentaField;
        
        private producto productoField;
        
        private double subtotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idLineaOrdenVenta {
            get {
                return this.idLineaOrdenVentaField;
            }
            set {
                this.idLineaOrdenVentaField = value;
                this.RaisePropertyChanged("idLineaOrdenVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
                this.RaisePropertyChanged("subtotal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pe.edu.pucp.softprog.services")]
    public partial class ordenVenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private cliente clienteField;
        
        private empleado empleadoField;
        
        private System.DateTime fechaHoraField;
        
        private bool fechaHoraFieldSpecified;
        
        private int idOrdenVentaField;
        
        private lineaOrdenVenta[] lineasOrdenVentaField;
        
        private double totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public empleado empleado {
            get {
                return this.empleadoField;
            }
            set {
                this.empleadoField = value;
                this.RaisePropertyChanged("empleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraSpecified {
            get {
                return this.fechaHoraFieldSpecified;
            }
            set {
                this.fechaHoraFieldSpecified = value;
                this.RaisePropertyChanged("fechaHoraSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idOrdenVenta {
            get {
                return this.idOrdenVentaField;
            }
            set {
                this.idOrdenVentaField = value;
                this.RaisePropertyChanged("idOrdenVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineasOrdenVenta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public lineaOrdenVenta[] lineasOrdenVenta {
            get {
                return this.lineasOrdenVentaField;
            }
            set {
                this.lineasOrdenVentaField = value;
                this.RaisePropertyChanged("lineasOrdenVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarClientesPorDNIoNombre", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class listarClientesPorDNIoNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DNIoNombre;
        
        public listarClientesPorDNIoNombreRequest() {
        }
        
        public listarClientesPorDNIoNombreRequest(string DNIoNombre) {
            this.DNIoNombre = DNIoNombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarClientesPorDNIoNombreResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class listarClientesPorDNIoNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.cliente[] @return;
        
        public listarClientesPorDNIoNombreResponse() {
        }
        
        public listarClientesPorDNIoNombreResponse(SoftProgWA.SoftProgServices.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClienteWSChannel : SoftProgWA.SoftProgServices.ClienteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteWSClient : System.ServiceModel.ClientBase<SoftProgWA.SoftProgServices.ClienteWS>, SoftProgWA.SoftProgServices.ClienteWS {
        
        public ClienteWSClient() {
        }
        
        public ClienteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreResponse SoftProgWA.SoftProgServices.ClienteWS.listarClientesPorDNIoNombre(SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreRequest request) {
            return base.Channel.listarClientesPorDNIoNombre(request);
        }
        
        public SoftProgWA.SoftProgServices.cliente[] listarClientesPorDNIoNombre(string DNIoNombre) {
            SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreRequest inValue = new SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreRequest();
            inValue.DNIoNombre = DNIoNombre;
            SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreResponse retVal = ((SoftProgWA.SoftProgServices.ClienteWS)(this)).listarClientesPorDNIoNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreResponse> SoftProgWA.SoftProgServices.ClienteWS.listarClientesPorDNIoNombreAsync(SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreRequest request) {
            return base.Channel.listarClientesPorDNIoNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreResponse> listarClientesPorDNIoNombreAsync(string DNIoNombre) {
            SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreRequest inValue = new SoftProgWA.SoftProgServices.listarClientesPorDNIoNombreRequest();
            inValue.DNIoNombre = DNIoNombre;
            return ((SoftProgWA.SoftProgServices.ClienteWS)(this)).listarClientesPorDNIoNombreAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="pe.edu.pucp.softprog.services", ConfigurationName="SoftProgServices.OrdenVentaWS")]
    public interface OrdenVentaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/OrdenVentaWS/insertarOrdenVentaRequest", ReplyAction="pe.edu.pucp.softprog.services/OrdenVentaWS/insertarOrdenVentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.insertarOrdenVentaResponse insertarOrdenVenta(SoftProgWA.SoftProgServices.insertarOrdenVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/OrdenVentaWS/insertarOrdenVentaRequest", ReplyAction="pe.edu.pucp.softprog.services/OrdenVentaWS/insertarOrdenVentaResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarOrdenVentaResponse> insertarOrdenVentaAsync(SoftProgWA.SoftProgServices.insertarOrdenVentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenVenta", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class insertarOrdenVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.ordenVenta ordenVenta;
        
        public insertarOrdenVentaRequest() {
        }
        
        public insertarOrdenVentaRequest(SoftProgWA.SoftProgServices.ordenVenta ordenVenta) {
            this.ordenVenta = ordenVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenVentaResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class insertarOrdenVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarOrdenVentaResponse() {
        }
        
        public insertarOrdenVentaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenVentaWSChannel : SoftProgWA.SoftProgServices.OrdenVentaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenVentaWSClient : System.ServiceModel.ClientBase<SoftProgWA.SoftProgServices.OrdenVentaWS>, SoftProgWA.SoftProgServices.OrdenVentaWS {
        
        public OrdenVentaWSClient() {
        }
        
        public OrdenVentaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenVentaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenVentaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenVentaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.insertarOrdenVentaResponse SoftProgWA.SoftProgServices.OrdenVentaWS.insertarOrdenVenta(SoftProgWA.SoftProgServices.insertarOrdenVentaRequest request) {
            return base.Channel.insertarOrdenVenta(request);
        }
        
        public int insertarOrdenVenta(SoftProgWA.SoftProgServices.ordenVenta ordenVenta) {
            SoftProgWA.SoftProgServices.insertarOrdenVentaRequest inValue = new SoftProgWA.SoftProgServices.insertarOrdenVentaRequest();
            inValue.ordenVenta = ordenVenta;
            SoftProgWA.SoftProgServices.insertarOrdenVentaResponse retVal = ((SoftProgWA.SoftProgServices.OrdenVentaWS)(this)).insertarOrdenVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarOrdenVentaResponse> SoftProgWA.SoftProgServices.OrdenVentaWS.insertarOrdenVentaAsync(SoftProgWA.SoftProgServices.insertarOrdenVentaRequest request) {
            return base.Channel.insertarOrdenVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarOrdenVentaResponse> insertarOrdenVentaAsync(SoftProgWA.SoftProgServices.ordenVenta ordenVenta) {
            SoftProgWA.SoftProgServices.insertarOrdenVentaRequest inValue = new SoftProgWA.SoftProgServices.insertarOrdenVentaRequest();
            inValue.ordenVenta = ordenVenta;
            return ((SoftProgWA.SoftProgServices.OrdenVentaWS)(this)).insertarOrdenVentaAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="pe.edu.pucp.softprog.services", ConfigurationName="SoftProgServices.CuentaUsuarioWS")]
    public interface CuentaUsuarioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/CuentaUsuarioWS/verificarCuentaUsuarioRequest", ReplyAction="pe.edu.pucp.softprog.services/CuentaUsuarioWS/verificarCuentaUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.verificarCuentaUsuarioResponse verificarCuentaUsuario(SoftProgWA.SoftProgServices.verificarCuentaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/CuentaUsuarioWS/verificarCuentaUsuarioRequest", ReplyAction="pe.edu.pucp.softprog.services/CuentaUsuarioWS/verificarCuentaUsuarioResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.verificarCuentaUsuarioResponse> verificarCuentaUsuarioAsync(SoftProgWA.SoftProgServices.verificarCuentaUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarCuentaUsuario", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class verificarCuentaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.cuentaUsuario cuentaUsuario;
        
        public verificarCuentaUsuarioRequest() {
        }
        
        public verificarCuentaUsuarioRequest(SoftProgWA.SoftProgServices.cuentaUsuario cuentaUsuario) {
            this.cuentaUsuario = cuentaUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarCuentaUsuarioResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class verificarCuentaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public verificarCuentaUsuarioResponse() {
        }
        
        public verificarCuentaUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CuentaUsuarioWSChannel : SoftProgWA.SoftProgServices.CuentaUsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuentaUsuarioWSClient : System.ServiceModel.ClientBase<SoftProgWA.SoftProgServices.CuentaUsuarioWS>, SoftProgWA.SoftProgServices.CuentaUsuarioWS {
        
        public CuentaUsuarioWSClient() {
        }
        
        public CuentaUsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuentaUsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaUsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaUsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.verificarCuentaUsuarioResponse SoftProgWA.SoftProgServices.CuentaUsuarioWS.verificarCuentaUsuario(SoftProgWA.SoftProgServices.verificarCuentaUsuarioRequest request) {
            return base.Channel.verificarCuentaUsuario(request);
        }
        
        public int verificarCuentaUsuario(SoftProgWA.SoftProgServices.cuentaUsuario cuentaUsuario) {
            SoftProgWA.SoftProgServices.verificarCuentaUsuarioRequest inValue = new SoftProgWA.SoftProgServices.verificarCuentaUsuarioRequest();
            inValue.cuentaUsuario = cuentaUsuario;
            SoftProgWA.SoftProgServices.verificarCuentaUsuarioResponse retVal = ((SoftProgWA.SoftProgServices.CuentaUsuarioWS)(this)).verificarCuentaUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.verificarCuentaUsuarioResponse> SoftProgWA.SoftProgServices.CuentaUsuarioWS.verificarCuentaUsuarioAsync(SoftProgWA.SoftProgServices.verificarCuentaUsuarioRequest request) {
            return base.Channel.verificarCuentaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.verificarCuentaUsuarioResponse> verificarCuentaUsuarioAsync(SoftProgWA.SoftProgServices.cuentaUsuario cuentaUsuario) {
            SoftProgWA.SoftProgServices.verificarCuentaUsuarioRequest inValue = new SoftProgWA.SoftProgServices.verificarCuentaUsuarioRequest();
            inValue.cuentaUsuario = cuentaUsuario;
            return ((SoftProgWA.SoftProgServices.CuentaUsuarioWS)(this)).verificarCuentaUsuarioAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="pe.edu.pucp.softprog.services", ConfigurationName="SoftProgServices.EmpleadoWS")]
    public interface EmpleadoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/EmpleadoWS/obtenerEmpleadoPorIdRequest", ReplyAction="pe.edu.pucp.softprog.services/EmpleadoWS/obtenerEmpleadoPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdResponse obtenerEmpleadoPorId(SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/EmpleadoWS/obtenerEmpleadoPorIdRequest", ReplyAction="pe.edu.pucp.softprog.services/EmpleadoWS/obtenerEmpleadoPorIdResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdResponse> obtenerEmpleadoPorIdAsync(SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/EmpleadoWS/listarEmpleadosTodosRequest", ReplyAction="pe.edu.pucp.softprog.services/EmpleadoWS/listarEmpleadosTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.listarEmpleadosTodosResponse listarEmpleadosTodos(SoftProgWA.SoftProgServices.listarEmpleadosTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/EmpleadoWS/listarEmpleadosTodosRequest", ReplyAction="pe.edu.pucp.softprog.services/EmpleadoWS/listarEmpleadosTodosResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarEmpleadosTodosResponse> listarEmpleadosTodosAsync(SoftProgWA.SoftProgServices.listarEmpleadosTodosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/EmpleadoWS/insertarEmpleadoRequest", ReplyAction="pe.edu.pucp.softprog.services/EmpleadoWS/insertarEmpleadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.insertarEmpleadoResponse insertarEmpleado(SoftProgWA.SoftProgServices.insertarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/EmpleadoWS/insertarEmpleadoRequest", ReplyAction="pe.edu.pucp.softprog.services/EmpleadoWS/insertarEmpleadoResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarEmpleadoResponse> insertarEmpleadoAsync(SoftProgWA.SoftProgServices.insertarEmpleadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/EmpleadoWS/modificarEmpleadoRequest", ReplyAction="pe.edu.pucp.softprog.services/EmpleadoWS/modificarEmpleadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.modificarEmpleadoResponse modificarEmpleado(SoftProgWA.SoftProgServices.modificarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/EmpleadoWS/modificarEmpleadoRequest", ReplyAction="pe.edu.pucp.softprog.services/EmpleadoWS/modificarEmpleadoResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.modificarEmpleadoResponse> modificarEmpleadoAsync(SoftProgWA.SoftProgServices.modificarEmpleadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/EmpleadoWS/eliminarEmpleadoRequest", ReplyAction="pe.edu.pucp.softprog.services/EmpleadoWS/eliminarEmpleadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.eliminarEmpleadoResponse eliminarEmpleado(SoftProgWA.SoftProgServices.eliminarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/EmpleadoWS/eliminarEmpleadoRequest", ReplyAction="pe.edu.pucp.softprog.services/EmpleadoWS/eliminarEmpleadoResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.eliminarEmpleadoResponse> eliminarEmpleadoAsync(SoftProgWA.SoftProgServices.eliminarEmpleadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEmpleadoPorId", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class obtenerEmpleadoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEmpleado;
        
        public obtenerEmpleadoPorIdRequest() {
        }
        
        public obtenerEmpleadoPorIdRequest(int idEmpleado) {
            this.idEmpleado = idEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEmpleadoPorIdResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class obtenerEmpleadoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.empleado @return;
        
        public obtenerEmpleadoPorIdResponse() {
        }
        
        public obtenerEmpleadoPorIdResponse(SoftProgWA.SoftProgServices.empleado @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpleadosTodos", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class listarEmpleadosTodosRequest {
        
        public listarEmpleadosTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpleadosTodosResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class listarEmpleadosTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.empleado[] @return;
        
        public listarEmpleadosTodosResponse() {
        }
        
        public listarEmpleadosTodosResponse(SoftProgWA.SoftProgServices.empleado[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpleado", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class insertarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.empleado arg0;
        
        public insertarEmpleadoRequest() {
        }
        
        public insertarEmpleadoRequest(SoftProgWA.SoftProgServices.empleado arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpleadoResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class insertarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEmpleadoResponse() {
        }
        
        public insertarEmpleadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEmpleado", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class modificarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.empleado arg0;
        
        public modificarEmpleadoRequest() {
        }
        
        public modificarEmpleadoRequest(SoftProgWA.SoftProgServices.empleado arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEmpleadoResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class modificarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarEmpleadoResponse() {
        }
        
        public modificarEmpleadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpleado", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class eliminarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarEmpleadoRequest() {
        }
        
        public eliminarEmpleadoRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpleadoResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class eliminarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarEmpleadoResponse() {
        }
        
        public eliminarEmpleadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpleadoWSChannel : SoftProgWA.SoftProgServices.EmpleadoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadoWSClient : System.ServiceModel.ClientBase<SoftProgWA.SoftProgServices.EmpleadoWS>, SoftProgWA.SoftProgServices.EmpleadoWS {
        
        public EmpleadoWSClient() {
        }
        
        public EmpleadoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdResponse SoftProgWA.SoftProgServices.EmpleadoWS.obtenerEmpleadoPorId(SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdRequest request) {
            return base.Channel.obtenerEmpleadoPorId(request);
        }
        
        public SoftProgWA.SoftProgServices.empleado obtenerEmpleadoPorId(int idEmpleado) {
            SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdRequest inValue = new SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdRequest();
            inValue.idEmpleado = idEmpleado;
            SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdResponse retVal = ((SoftProgWA.SoftProgServices.EmpleadoWS)(this)).obtenerEmpleadoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdResponse> SoftProgWA.SoftProgServices.EmpleadoWS.obtenerEmpleadoPorIdAsync(SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdRequest request) {
            return base.Channel.obtenerEmpleadoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdResponse> obtenerEmpleadoPorIdAsync(int idEmpleado) {
            SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdRequest inValue = new SoftProgWA.SoftProgServices.obtenerEmpleadoPorIdRequest();
            inValue.idEmpleado = idEmpleado;
            return ((SoftProgWA.SoftProgServices.EmpleadoWS)(this)).obtenerEmpleadoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.listarEmpleadosTodosResponse SoftProgWA.SoftProgServices.EmpleadoWS.listarEmpleadosTodos(SoftProgWA.SoftProgServices.listarEmpleadosTodosRequest request) {
            return base.Channel.listarEmpleadosTodos(request);
        }
        
        public SoftProgWA.SoftProgServices.empleado[] listarEmpleadosTodos() {
            SoftProgWA.SoftProgServices.listarEmpleadosTodosRequest inValue = new SoftProgWA.SoftProgServices.listarEmpleadosTodosRequest();
            SoftProgWA.SoftProgServices.listarEmpleadosTodosResponse retVal = ((SoftProgWA.SoftProgServices.EmpleadoWS)(this)).listarEmpleadosTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarEmpleadosTodosResponse> SoftProgWA.SoftProgServices.EmpleadoWS.listarEmpleadosTodosAsync(SoftProgWA.SoftProgServices.listarEmpleadosTodosRequest request) {
            return base.Channel.listarEmpleadosTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarEmpleadosTodosResponse> listarEmpleadosTodosAsync() {
            SoftProgWA.SoftProgServices.listarEmpleadosTodosRequest inValue = new SoftProgWA.SoftProgServices.listarEmpleadosTodosRequest();
            return ((SoftProgWA.SoftProgServices.EmpleadoWS)(this)).listarEmpleadosTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.insertarEmpleadoResponse SoftProgWA.SoftProgServices.EmpleadoWS.insertarEmpleado(SoftProgWA.SoftProgServices.insertarEmpleadoRequest request) {
            return base.Channel.insertarEmpleado(request);
        }
        
        public int insertarEmpleado(SoftProgWA.SoftProgServices.empleado arg0) {
            SoftProgWA.SoftProgServices.insertarEmpleadoRequest inValue = new SoftProgWA.SoftProgServices.insertarEmpleadoRequest();
            inValue.arg0 = arg0;
            SoftProgWA.SoftProgServices.insertarEmpleadoResponse retVal = ((SoftProgWA.SoftProgServices.EmpleadoWS)(this)).insertarEmpleado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarEmpleadoResponse> SoftProgWA.SoftProgServices.EmpleadoWS.insertarEmpleadoAsync(SoftProgWA.SoftProgServices.insertarEmpleadoRequest request) {
            return base.Channel.insertarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarEmpleadoResponse> insertarEmpleadoAsync(SoftProgWA.SoftProgServices.empleado arg0) {
            SoftProgWA.SoftProgServices.insertarEmpleadoRequest inValue = new SoftProgWA.SoftProgServices.insertarEmpleadoRequest();
            inValue.arg0 = arg0;
            return ((SoftProgWA.SoftProgServices.EmpleadoWS)(this)).insertarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.modificarEmpleadoResponse SoftProgWA.SoftProgServices.EmpleadoWS.modificarEmpleado(SoftProgWA.SoftProgServices.modificarEmpleadoRequest request) {
            return base.Channel.modificarEmpleado(request);
        }
        
        public int modificarEmpleado(SoftProgWA.SoftProgServices.empleado arg0) {
            SoftProgWA.SoftProgServices.modificarEmpleadoRequest inValue = new SoftProgWA.SoftProgServices.modificarEmpleadoRequest();
            inValue.arg0 = arg0;
            SoftProgWA.SoftProgServices.modificarEmpleadoResponse retVal = ((SoftProgWA.SoftProgServices.EmpleadoWS)(this)).modificarEmpleado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.modificarEmpleadoResponse> SoftProgWA.SoftProgServices.EmpleadoWS.modificarEmpleadoAsync(SoftProgWA.SoftProgServices.modificarEmpleadoRequest request) {
            return base.Channel.modificarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.modificarEmpleadoResponse> modificarEmpleadoAsync(SoftProgWA.SoftProgServices.empleado arg0) {
            SoftProgWA.SoftProgServices.modificarEmpleadoRequest inValue = new SoftProgWA.SoftProgServices.modificarEmpleadoRequest();
            inValue.arg0 = arg0;
            return ((SoftProgWA.SoftProgServices.EmpleadoWS)(this)).modificarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.eliminarEmpleadoResponse SoftProgWA.SoftProgServices.EmpleadoWS.eliminarEmpleado(SoftProgWA.SoftProgServices.eliminarEmpleadoRequest request) {
            return base.Channel.eliminarEmpleado(request);
        }
        
        public int eliminarEmpleado(int arg0) {
            SoftProgWA.SoftProgServices.eliminarEmpleadoRequest inValue = new SoftProgWA.SoftProgServices.eliminarEmpleadoRequest();
            inValue.arg0 = arg0;
            SoftProgWA.SoftProgServices.eliminarEmpleadoResponse retVal = ((SoftProgWA.SoftProgServices.EmpleadoWS)(this)).eliminarEmpleado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.eliminarEmpleadoResponse> SoftProgWA.SoftProgServices.EmpleadoWS.eliminarEmpleadoAsync(SoftProgWA.SoftProgServices.eliminarEmpleadoRequest request) {
            return base.Channel.eliminarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.eliminarEmpleadoResponse> eliminarEmpleadoAsync(int arg0) {
            SoftProgWA.SoftProgServices.eliminarEmpleadoRequest inValue = new SoftProgWA.SoftProgServices.eliminarEmpleadoRequest();
            inValue.arg0 = arg0;
            return ((SoftProgWA.SoftProgServices.EmpleadoWS)(this)).eliminarEmpleadoAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="pe.edu.pucp.softprog.services", ConfigurationName="SoftProgServices.ProductoWS")]
    public interface ProductoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/ProductoWS/listarProductosPorNombreRequest", ReplyAction="pe.edu.pucp.softprog.services/ProductoWS/listarProductosPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.listarProductosPorNombreResponse listarProductosPorNombre(SoftProgWA.SoftProgServices.listarProductosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/ProductoWS/listarProductosPorNombreRequest", ReplyAction="pe.edu.pucp.softprog.services/ProductoWS/listarProductosPorNombreResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarProductosPorNombreResponse> listarProductosPorNombreAsync(SoftProgWA.SoftProgServices.listarProductosPorNombreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosPorNombre", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class listarProductosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarProductosPorNombreRequest() {
        }
        
        public listarProductosPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosPorNombreResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class listarProductosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.producto[] @return;
        
        public listarProductosPorNombreResponse() {
        }
        
        public listarProductosPorNombreResponse(SoftProgWA.SoftProgServices.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoWSChannel : SoftProgWA.SoftProgServices.ProductoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoWSClient : System.ServiceModel.ClientBase<SoftProgWA.SoftProgServices.ProductoWS>, SoftProgWA.SoftProgServices.ProductoWS {
        
        public ProductoWSClient() {
        }
        
        public ProductoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.listarProductosPorNombreResponse SoftProgWA.SoftProgServices.ProductoWS.listarProductosPorNombre(SoftProgWA.SoftProgServices.listarProductosPorNombreRequest request) {
            return base.Channel.listarProductosPorNombre(request);
        }
        
        public SoftProgWA.SoftProgServices.producto[] listarProductosPorNombre(string nombre) {
            SoftProgWA.SoftProgServices.listarProductosPorNombreRequest inValue = new SoftProgWA.SoftProgServices.listarProductosPorNombreRequest();
            inValue.nombre = nombre;
            SoftProgWA.SoftProgServices.listarProductosPorNombreResponse retVal = ((SoftProgWA.SoftProgServices.ProductoWS)(this)).listarProductosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarProductosPorNombreResponse> SoftProgWA.SoftProgServices.ProductoWS.listarProductosPorNombreAsync(SoftProgWA.SoftProgServices.listarProductosPorNombreRequest request) {
            return base.Channel.listarProductosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarProductosPorNombreResponse> listarProductosPorNombreAsync(string nombre) {
            SoftProgWA.SoftProgServices.listarProductosPorNombreRequest inValue = new SoftProgWA.SoftProgServices.listarProductosPorNombreRequest();
            inValue.nombre = nombre;
            return ((SoftProgWA.SoftProgServices.ProductoWS)(this)).listarProductosPorNombreAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="pe.edu.pucp.softprog.services", ConfigurationName="SoftProgServices.AreaWS")]
    public interface AreaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/insertarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/insertarAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.insertarAreaResponse insertarArea(SoftProgWA.SoftProgServices.insertarAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/insertarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/insertarAreaResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarAreaResponse> insertarAreaAsync(SoftProgWA.SoftProgServices.insertarAreaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/obtenerAreaPorIdRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/obtenerAreaPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse obtenerAreaPorId(SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/obtenerAreaPorIdRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/obtenerAreaPorIdResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse> obtenerAreaPorIdAsync(SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/eliminarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/eliminarAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.eliminarAreaResponse eliminarArea(SoftProgWA.SoftProgServices.eliminarAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/eliminarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/eliminarAreaResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.eliminarAreaResponse> eliminarAreaAsync(SoftProgWA.SoftProgServices.eliminarAreaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/listarAreasTodasRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/listarAreasTodasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.listarAreasTodasResponse listarAreasTodas(SoftProgWA.SoftProgServices.listarAreasTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/listarAreasTodasRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/listarAreasTodasResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarAreasTodasResponse> listarAreasTodasAsync(SoftProgWA.SoftProgServices.listarAreasTodasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/modificarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/modificarAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWA.SoftProgServices.modificarAreaResponse modificarArea(SoftProgWA.SoftProgServices.modificarAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="pe.edu.pucp.softprog.services/AreaWS/modificarAreaRequest", ReplyAction="pe.edu.pucp.softprog.services/AreaWS/modificarAreaResponse")]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.modificarAreaResponse> modificarAreaAsync(SoftProgWA.SoftProgServices.modificarAreaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarArea", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class insertarAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.area arg0;
        
        public insertarAreaRequest() {
        }
        
        public insertarAreaRequest(SoftProgWA.SoftProgServices.area arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAreaResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class insertarAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarAreaResponse() {
        }
        
        public insertarAreaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAreaPorId", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class obtenerAreaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idArea;
        
        public obtenerAreaPorIdRequest() {
        }
        
        public obtenerAreaPorIdRequest(int idArea) {
            this.idArea = idArea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerAreaPorIdResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class obtenerAreaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.area @return;
        
        public obtenerAreaPorIdResponse() {
        }
        
        public obtenerAreaPorIdResponse(SoftProgWA.SoftProgServices.area @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarArea", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class eliminarAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarAreaRequest() {
        }
        
        public eliminarAreaRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarAreaResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class eliminarAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarAreaResponse() {
        }
        
        public eliminarAreaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAreasTodas", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class listarAreasTodasRequest {
        
        public listarAreasTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAreasTodasResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class listarAreasTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.area[] @return;
        
        public listarAreasTodasResponse() {
        }
        
        public listarAreasTodasResponse(SoftProgWA.SoftProgServices.area[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarArea", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class modificarAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWA.SoftProgServices.area arg0;
        
        public modificarAreaRequest() {
        }
        
        public modificarAreaRequest(SoftProgWA.SoftProgServices.area arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarAreaResponse", WrapperNamespace="pe.edu.pucp.softprog.services", IsWrapped=true)]
    public partial class modificarAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pe.edu.pucp.softprog.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarAreaResponse() {
        }
        
        public modificarAreaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AreaWSChannel : SoftProgWA.SoftProgServices.AreaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AreaWSClient : System.ServiceModel.ClientBase<SoftProgWA.SoftProgServices.AreaWS>, SoftProgWA.SoftProgServices.AreaWS {
        
        public AreaWSClient() {
        }
        
        public AreaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AreaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.insertarAreaResponse SoftProgWA.SoftProgServices.AreaWS.insertarArea(SoftProgWA.SoftProgServices.insertarAreaRequest request) {
            return base.Channel.insertarArea(request);
        }
        
        public int insertarArea(SoftProgWA.SoftProgServices.area arg0) {
            SoftProgWA.SoftProgServices.insertarAreaRequest inValue = new SoftProgWA.SoftProgServices.insertarAreaRequest();
            inValue.arg0 = arg0;
            SoftProgWA.SoftProgServices.insertarAreaResponse retVal = ((SoftProgWA.SoftProgServices.AreaWS)(this)).insertarArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarAreaResponse> SoftProgWA.SoftProgServices.AreaWS.insertarAreaAsync(SoftProgWA.SoftProgServices.insertarAreaRequest request) {
            return base.Channel.insertarAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.insertarAreaResponse> insertarAreaAsync(SoftProgWA.SoftProgServices.area arg0) {
            SoftProgWA.SoftProgServices.insertarAreaRequest inValue = new SoftProgWA.SoftProgServices.insertarAreaRequest();
            inValue.arg0 = arg0;
            return ((SoftProgWA.SoftProgServices.AreaWS)(this)).insertarAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse SoftProgWA.SoftProgServices.AreaWS.obtenerAreaPorId(SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest request) {
            return base.Channel.obtenerAreaPorId(request);
        }
        
        public SoftProgWA.SoftProgServices.area obtenerAreaPorId(int idArea) {
            SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest inValue = new SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest();
            inValue.idArea = idArea;
            SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse retVal = ((SoftProgWA.SoftProgServices.AreaWS)(this)).obtenerAreaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse> SoftProgWA.SoftProgServices.AreaWS.obtenerAreaPorIdAsync(SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest request) {
            return base.Channel.obtenerAreaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.obtenerAreaPorIdResponse> obtenerAreaPorIdAsync(int idArea) {
            SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest inValue = new SoftProgWA.SoftProgServices.obtenerAreaPorIdRequest();
            inValue.idArea = idArea;
            return ((SoftProgWA.SoftProgServices.AreaWS)(this)).obtenerAreaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.eliminarAreaResponse SoftProgWA.SoftProgServices.AreaWS.eliminarArea(SoftProgWA.SoftProgServices.eliminarAreaRequest request) {
            return base.Channel.eliminarArea(request);
        }
        
        public int eliminarArea(int arg0) {
            SoftProgWA.SoftProgServices.eliminarAreaRequest inValue = new SoftProgWA.SoftProgServices.eliminarAreaRequest();
            inValue.arg0 = arg0;
            SoftProgWA.SoftProgServices.eliminarAreaResponse retVal = ((SoftProgWA.SoftProgServices.AreaWS)(this)).eliminarArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.eliminarAreaResponse> SoftProgWA.SoftProgServices.AreaWS.eliminarAreaAsync(SoftProgWA.SoftProgServices.eliminarAreaRequest request) {
            return base.Channel.eliminarAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.eliminarAreaResponse> eliminarAreaAsync(int arg0) {
            SoftProgWA.SoftProgServices.eliminarAreaRequest inValue = new SoftProgWA.SoftProgServices.eliminarAreaRequest();
            inValue.arg0 = arg0;
            return ((SoftProgWA.SoftProgServices.AreaWS)(this)).eliminarAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.listarAreasTodasResponse SoftProgWA.SoftProgServices.AreaWS.listarAreasTodas(SoftProgWA.SoftProgServices.listarAreasTodasRequest request) {
            return base.Channel.listarAreasTodas(request);
        }
        
        public SoftProgWA.SoftProgServices.area[] listarAreasTodas() {
            SoftProgWA.SoftProgServices.listarAreasTodasRequest inValue = new SoftProgWA.SoftProgServices.listarAreasTodasRequest();
            SoftProgWA.SoftProgServices.listarAreasTodasResponse retVal = ((SoftProgWA.SoftProgServices.AreaWS)(this)).listarAreasTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarAreasTodasResponse> SoftProgWA.SoftProgServices.AreaWS.listarAreasTodasAsync(SoftProgWA.SoftProgServices.listarAreasTodasRequest request) {
            return base.Channel.listarAreasTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.listarAreasTodasResponse> listarAreasTodasAsync() {
            SoftProgWA.SoftProgServices.listarAreasTodasRequest inValue = new SoftProgWA.SoftProgServices.listarAreasTodasRequest();
            return ((SoftProgWA.SoftProgServices.AreaWS)(this)).listarAreasTodasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWA.SoftProgServices.modificarAreaResponse SoftProgWA.SoftProgServices.AreaWS.modificarArea(SoftProgWA.SoftProgServices.modificarAreaRequest request) {
            return base.Channel.modificarArea(request);
        }
        
        public int modificarArea(SoftProgWA.SoftProgServices.area arg0) {
            SoftProgWA.SoftProgServices.modificarAreaRequest inValue = new SoftProgWA.SoftProgServices.modificarAreaRequest();
            inValue.arg0 = arg0;
            SoftProgWA.SoftProgServices.modificarAreaResponse retVal = ((SoftProgWA.SoftProgServices.AreaWS)(this)).modificarArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.modificarAreaResponse> SoftProgWA.SoftProgServices.AreaWS.modificarAreaAsync(SoftProgWA.SoftProgServices.modificarAreaRequest request) {
            return base.Channel.modificarAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWA.SoftProgServices.modificarAreaResponse> modificarAreaAsync(SoftProgWA.SoftProgServices.area arg0) {
            SoftProgWA.SoftProgServices.modificarAreaRequest inValue = new SoftProgWA.SoftProgServices.modificarAreaRequest();
            inValue.arg0 = arg0;
            return ((SoftProgWA.SoftProgServices.AreaWS)(this)).modificarAreaAsync(inValue);
        }
    }
}
